package com.example.zlq_pc.tvdemo4.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zlq_pc.tvdemo4.entity.VideoEntity;

import com.example.zlq_pc.tvdemo4.entity.VideoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoEntityDaoConfig;

    private final VideoEntityDao videoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoEntityDaoConfig = daoConfigMap.get(VideoEntityDao.class).clone();
        videoEntityDaoConfig.initIdentityScope(type);

        videoEntityDao = new VideoEntityDao(videoEntityDaoConfig, this);

        registerDao(VideoEntity.class, videoEntityDao);
    }
    
    public void clear() {
        videoEntityDaoConfig.getIdentityScope().clear();
    }

    public VideoEntityDao getVideoEntityDao() {
        return videoEntityDao;
    }

}
